# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb7ef69a2955c9906d1e6d46065bafc6cdfd1421c8fe4973c8d6a1450dbf70ebca1f97e647a4eeeaafbfb87e720d5cb3f2ef23da4509277be80237f507f5a427

test:
  secret_key_base: a70ebd2f710106e45b028b0f397290a575314fc9814320ae8e31e8f2516215248bd11231a397a5b86bf5fb944a82cb0363dd82aa7bcc0bd710c912788f7aea57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
